# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{onfire}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nick Sutterer"]
  s.date = %q{2010-03-19}
  s.description = %q{Have bubbling events and observers in all your Ruby objects.}
  s.email = %q{apotonick@gmail.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "README.textile",
     "Rakefile",
     "lib/onfire.rb",
     "lib/onfire/event.rb",
     "lib/onfire/event_table.rb",
     "lib/onfire/version.rb",
     "test/event_table_test.rb",
     "test/event_test.rb",
     "test/onfire_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/apotonick/onfire}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Have bubbling events and observers in all your Ruby objects.}
  s.test_files = [
    "test/onfire_test.rb",
     "test/test_helper.rb",
     "test/event_table_test.rb",
     "test/event_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

